version: 2
jobs:
  build:
    working_directory: ~/auxilium-app
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: "sudo npm install -g yarn@latest"
      - run:
          name: Install global dependencies
          command: "sudo yarn global add lerna"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./packages/Auxilium-App/node_modules
            - ./packages/Auxilium-Server/node_modules
  deploy_mobile:
    working_directory: ~/auxilium-app
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run:
          name: Install global dependencies
          command: sudo npm i -g yarn@latest && sudo yarn global add expo-cli lerna
      - run:
          name: Install dependencies
          command: lerna bootstrap --scope auxilium-app
      - run:
          name: Login to Expo
          command: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Publish to Expo
          command: lerna exec --scope auxilium-app "yarn publish:app"
  deploy_backend:
    working_directory: ~/auxilium-app
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Push backend to Heroku
          command: |
            git subtree push --prefix packages/Auxilium-Server https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy_mobile:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - prepare-staging
                - master
      - deploy_backend:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - prepare-staging
                - master
