version: 2
jobs:
  deploy_mobile:
    working_directory: ~/auxilium-app
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run:
          name: Install global dependencies
          command: sudo npm i -g yarn@latest && sudo yarn global add expo-cli lerna
      - run:
          name: Install dependencies
          command: lerna bootstrap --scope auxilium-app
      - run:
          name: Login to Expo
          command: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Publish to Expo
          command: |
            if ["${CIRCLE_BRANCH}" == "staging"]; then
              lerna exec --scope auxilium-app "yarn publish:app --release-channel staging"
            elif ["${CIRCLE_BRANCH}" == "master"]; then
              lerna exec --scope auxilium-app "yarn publish:app --release-channel prod"
            fi
  deploy_backend:
    working_directory: ~/auxilium-app
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Push backend to Heroku
          command: |
            git subtree push --prefix packages/Auxilium-Server https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_mobile:
          filters:
            branches:
              only:
                - staging
                - master
      - deploy_backend:
          filters:
            branches:
              only:
                - staging
                - master
