name: Lint and Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - master
      - staging

jobs:
  test:
    name: Run static tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install dependencies
      run: |
        cd app && yarn && cd ..
        cd dashboard && yarn && cd ..
        cd server && yarn

    - name: Run lint
      run: |
        cd app && yarn lint && cd ..
        cd dashboard && yarn lint && cd ..
        cd server && yarn lint

    - name: Run typecheck
      run: |
        cd app && yarn tsc && cd ..
        cd dashboard && yarn tsc && cd ..
        cd server && yarn tsc
